apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: peerprep-user
  name: peerprep-user
  namespace: peerprep
spec:
  replicas: 2
  selector:
    matchLabels:
      app: peerprep-user
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: peerprep-user
    spec:
      containers:
        - image: alxarkar/user-service:latest
          name: peerprep-user
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: 0.5
              memory: 1G
          env:
            - name: DB_CLOUD_URI
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: DB_CLOUD_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: peerprep-secret
                  key: JWT_SECRET
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: peerprep-config
                  key: USER_PORT
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: peerprep-config
                  key: USER_ENV
status: {}
