services:
  question-db:
    build:
      context: ./db/question-db
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    environment:
    - MONGO_INITDB_DATABASE=questions_db
    - INIT_QUESTION_COLLECTION=questions
  question-service:
    depends_on:
      - question-db
    build:
      context: ./question-service
      dockerfile: Dockerfile
    environment:
      - QUESTION_DB_URL=mongodb://question-db:27017 # note that the URL is referencing the container name
      - DB_NAME=questions_db
      - COLELCTION_NAME=questions
    ports:
      - "8000:8000"
