apiVersion: v1
kind: Service
metadata:
  name: peerprep-question-grpc
  namespace: peerprep
spec:
  selector:
    app: peerprep-question
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP
