apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: question-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-question
  minReplicas: 1
  maxReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 80