apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: collab-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-collab
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 80
