apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: collab-redis
  name: collab-redis
  namespace: peerprep
spec:
  containers:
    - image: redis:alpine3.20
      name: collab-redis
      resources: {}
      ports:
        - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
