apiVersion: v1
kind: Service
metadata:
  name: collab-redis-service
  namespace: peerprep
spec:
  selector:
    app: collab-redis
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  type: ClusterIP
