apiVersion: v1
kind: Service
metadata:
  name: peerprep-matching-service
  namespace: peerprep
  labels:
    app: peerprep-matching
spec:
  selector:
    app: peerprep-matching
  ports:
    - port: 8000 # Service port
      targetPort: 8000 # Container port exposed by the user-service container
      protocol: TCP
      name: http
  type: ClusterIP # Internal access within the cluster
