apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  namespace: peerprep
  annotations:
    nginx.ingress.kubernetes.io/websocket-services: peerprep-collab-service
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "http://localhost:3000, https://peerprep-frontend-418708025075.asia-southeast1.run.app" # add Cloud Run here
    nginx.ingress.kubernetes.io/ingress.regional-static-ip-name: "peerprep-ip"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - peerpreps.com
      secretName: letsencrypt-prod
  rules:
    - host: peerpreps.com
      http:
        paths:
          - path: /user-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: peerprep-user-service
                port:
                  number: 8000
          - path: /question-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: peerprep-question-service
                port:
                  number: 8000
          - path: /matching-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: peerprep-matching-service
                port:
                  number: 8000
          - path: /collab-service/(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: peerprep-collab-service
                port:
                  number: 8000
