apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: matching-hpa
  namespace: peerprep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: peerprep-matching
  minReplicas: 1
  maxReplicas: 2
  targetRAMUtilizationPercentage: 80
