apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: matchmaker-redis
  name: matchmaker-redis
  namespace: peerprep
spec:
  containers:
    - image: redis:alpine3.20
      name: matchmaker-redis
      resources: {}
      ports:
        - containerPort: 6379
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
