name: Build and Deploy Peerprep

on:
  push:
    branches:
      - main

env:
  LATEST_TAG: latest
  CLOUD_RUN_FRONTEND: peerprep-frontend
  ARTIFACT_REGISTRY: asia-southeast1-docker.pkg.dev
  ARTIFACT_REPOSITORY: peerprep-g40

jobs:
  build-and-push:
    name: Publish to Google Artifact Registry and DockerHub
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    strategy:
      matrix:
        service:
          - name: user-service
            context: "{{defaultContext}}:/backend/user-service"
          - name: question-service
            context: "{{defaultContext}}:/backend/question-service"
          - name: matching-service
            context: "{{defaultContext}}:/backend/matching-service"
          - name: collab-service
            context: "{{defaultContext}}:/backend/collab-service"
          - name: peerprep-frontend
            context: "{{defaultContext}}:/frontend"
          # Add additional services as needed

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Auth Google Cloud SDK
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_FRONTEND_SERVICE_ACCOUNT }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Configure Docker for Google Artifact Registry
        run: |
          gcloud auth configure-docker \
              ${{ env.ARTIFACT_REGISTRY }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: ${{ matrix.service.context }}
          push: true
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/${{ matrix.service.name }}:${{ env.LATEST_TAG }}
            ${{ env.ARTIFACT_REGISTRY }}/${{ vars.GCP_PROJECT_ID }}/${{ env.ARTIFACT_REPOSITORY }}/${{ matrix.service.name }}:${{ env.LATEST_TAG }}

  deploy-frontend:
    name: Deploy frontend to Cloud Run
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_FRONTEND_SERVICE_ACCOUNT }}
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: Deploy frontend to Cloud Run
        run: |
          gcloud run deploy ${{ env.CLOUD_RUN_FRONTEND }} \
            --image gcr.io/${{ vars.GCP_PROJECT_ID }}/${{ env.CLOUD_RUN_FRONTEND }}:latest \
            --platform managed \
            --region asia-southeast1 \
            --allow-unauthenticated
